import unittest
from .ai_content_detector import analyze_text_for_ai_content
from .fake_content_verifier import analyze_text_for_fake_content

class TestAIAndFakeContent(unittest.TestCase):

    def test_ai_content_detection(self):
        ai_text = "As an AI language model, I am designed to provide helpful information. Furthermore, in conclusion, this text looks like it was generated by an AI."
        result = analyze_text_for_ai_content(ai_text)
        self.assertTrue(result["is_ai_generated"])
        self.assertIn("Found AI-typical phrase: 'as an ai language model'", result["indicators_found"])

    def test_human_content_detection(self):
        human_text = "Hey there, I just wanted to say hi. I hope you have a great day! No robotic stuff here."
        result = analyze_text_for_ai_content(human_text)
        self.assertFalse(result["is_ai_generated"])

    def test_fake_content_verification(self):
        fake_text = "SHOCKING BOMBSHELL!!! You won't believe what happened next! This secret will shock you."
        result = analyze_text_for_fake_content(fake_text)
        self.assertGreater(result["score"], 3.0)
        self.assertIn("Found sensationalist keyword: 'shocking'", result["indicators_found"])
        self.assertIn("Found clickbait pattern: 'you won't believe'", result["indicators_found"])

if __name__ == '__main__':
    unittest.main()
