import React, { useState } from 'react';

function AIContentDetector() {
    const [text, setText] = useState('');
    const [result, setResult] = useState(null);
    const [loading, setLoading] = useState(false);

    const handleAnalyze = () => {
        setLoading(true);
        fetch('/analyze/ai-content', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ text }),
        })
            .then((res) => res.json())
            .then((data) => {
                setResult(data);
                setLoading(false);
            })
            .catch((error) => {
                console.error('Error:', error);
                setLoading(false);
            });
    };

    return (
        <div className="analyzer-container">
            <h2>AI Content Detector</h2>
            <p>Paste text below to check if it was likely generated by an AI.</p>
            <textarea
                value={text}
                onChange={(e) => setText(e.target.value)}
                placeholder="Paste text here..."
                rows="10"
                style={{ width: '100%', marginBottom: '10px' }}
            />
            <br />
            <button onClick={handleAnalyze} disabled={loading || !text}>
                {loading ? 'Analyzing...' : 'Detect AI Content'}
            </button>
            {result && (
                <div className="results">
                    <h3>Analysis Results</h3>
                    <p><strong>Assessment:</strong> {result.assessment}</p>
                    <p><strong>Confidence Score:</strong> {result.score}</p>
                    {result.indicators_found.length > 0 && (
                        <>
                            <h4>Indicators Found:</h4>
                            <ul>
                                {result.indicators_found.map((indicator, index) => (
                                    <li key={index}>{indicator}</li>
                                ))}
                            </ul>
                        </>
                    )}
                </div>
            )}
        </div>
    );
}

export default AIContentDetector;
