import React from 'react';

const tools = [
  {
    id: 'scam',
    name: 'Scam Analyzer',
    description: 'Heuristic-based detection for phishing and fraudulent messages.',
    icon: '🛡️'
  },
  {
    id: 'fake-news',
    name: 'Fake News Detector',
    description: 'Analyze news articles for sensationalism and misinformation patterns.',
    icon: '📰'
  },
  {
    id: 'ai-content',
    name: 'AI Content Detector',
    description: 'Identify text generated by large language models.',
    icon: '🤖'
  },
  {
    id: 'fake-content',
    name: 'Fake Content Verifier',
    description: 'Verify the authenticity of digital media and profiles.',
    icon: '🔍'
  },
  {
    id: 'fbi-game',
    name: 'FBI AR Game',
    description: 'Immersive training for identifying security threats in AR.',
    icon: '🕶️'
  },
  {
    id: 'supply-chain',
    name: 'Logistics Digital Twin',
    description: '3D warehouse simulation and blockchain-backed logistics tracking.',
    icon: '📦'
  },
  {
    id: 'assistance',
    name: 'Official Assistance',
    description: 'Integrated support tools for Police, Military, Gendarmerie, Mobile Operators, and Operational Security.',
    icon: '🛡️'
  }
];

export default function Marketplace({ setView }) {
  return (
    <div className="marketplace-container">
      <section className="hero">
        <h1>Global Security Marketplace</h1>
        <p className="official-domain">Official Domain: <strong>global-security-platform.com</strong></p>
        <p>The centralized hub for your digital protection needs. Secure your communication, verify your data, and optimize your logistics with our AI-powered suite.</p>
      </section>

      <div className="tool-grid">
        {tools.map((tool) => (
          <div key={tool.id} className="tool-card" onClick={() => setView(tool.id)}>
            <div className="tool-icon">{tool.icon}</div>
            <h3>{tool.name}</h3>
            <p>{tool.description}</p>
            <button className="open-btn">Launch App</button>
          </div>
        ))}
      </div>

      <style jsx>{`
        .marketplace-container {
          padding: 40px 20px;
          max-width: 1200px;
          margin: 0 auto;
        }
        .hero {
          text-align: center;
          margin-bottom: 50px;
          padding: 40px;
          background: rgba(255, 255, 255, 0.05);
          border-radius: 15px;
        }
        .official-domain {
          font-size: 1.2rem;
          color: #61dafb;
          margin: 10px 0;
        }
        .tool-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
          gap: 25px;
        }
        .tool-card {
          background: #282c34;
          border: 1px solid #444;
          border-radius: 12px;
          padding: 25px;
          text-align: left;
          transition: transform 0.2s, box-shadow 0.2s;
          cursor: pointer;
          display: flex;
          flex-direction: column;
        }
        .tool-card:hover {
          transform: translateY(-5px);
          box-shadow: 0 10px 20px rgba(0,0,0,0.3);
          border-color: #61dafb;
        }
        .tool-icon {
          font-size: 3rem;
          margin-bottom: 15px;
        }
        .tool-card h3 {
          margin: 0 0 10px 0;
          color: #61dafb;
        }
        .tool-card p {
          color: #ccc;
          font-size: 0.95rem;
          line-height: 1.5;
          flex-grow: 1;
          margin-bottom: 20px;
        }
        .open-btn {
          background: #61dafb;
          color: #282c34;
          border: none;
          padding: 10px;
          border-radius: 6px;
          font-weight: bold;
          cursor: pointer;
        }
      `}</style>
    </div>
  );
}
